### PR TITLE
Improve throughput

### PR DESCRIPTION
**Pull request by MikeGitb**
This solves the problem of `sweep_device_get_scan` skiping every second scan mentioned in #16. 

Every call to `sweep_device_get_scan` now simply returns all packets up to and including the next packet that has the sync bit set. When the function is called in a loop this should always return a full 360° scan except for the first call and it is up to the user to decide, whether or not he wants to discard that first scan. This is also pretty much the semantics needed when using a worker thread.

As a sideffect it also simplifies the code a bit ;)

### CODE REVIEW

**Comment by daniel-j-h** [comment]
Thank you! Just tested with device - works as advertised :)

**Comment by dcyoung** [comment]
I haven't tried this out yet, but from the description it sounds like the last entry of the returned scan is the sync reading of the following scan. If this is the case, we really should be discarding and not including this last entry as it will disturb anything that assumes readings of a scan are arranged in order of increasing degree. Any attempt to order the readings by azimuth would then result in readings that are out of chronological order. Until we get the worker thread and queue implementation in place, we should not include the sync reading.

**Comment by MikeGitb** [comment]
@dcyoung: 
> I haven't tried this out yet, but from the description it sounds like the last entry of the returned scan is the sync reading of the following scan.

Correct.

> as it will disturb anything that assumes readings of a scan are arranged in order of increasing degree

Is this something you want to guarantee? If so, instead of dropping the sync reading we can store it for the next call to `get_scan`. Makes the code a bit more complicated, but nothing I'd call troublesome.

**Comment by dcyoung** [comment]
We definitely want to guarantee that a scan will contain only the readings accrued during a single rotation. I think that is more important than avoiding the loss of a single reading. 

Part of the SDK design was to avoid any persistent or global variables. Seems like holding onto a single reading between scans would conflict with that. And it would be rather ugly. I don't see much harm in losing a single reading until the scan worker is in place, which should hopefully be ASAP.

**Comment by MikeGitb** [comment]
@dcyoung: 

> We definitely want to guarantee that a scan will contain only the readings accrued during a single rotation. I think that is more important than avoiding the loss of a single reading.

Are you defining a rotation as starting at 0 degree and ending at 360-epsilon? Or any interval that spans 360degrees? Neither the current implementation nor my proposed fix would return more than 360 degrees. But yes currently one scan is (0, 0] instead of [0, 0).

> Part of the SDK design was to avoid any persistent or global variables. Seems like holding onto a single reading between scans would conflict with that. And it would be rather ugly.

well, it would only require one member variable in sweep_device and the logic would not be more complicated than what it looked before this PR. But if this is a temporal fix anyway I agree - lets just dump it.

> I don't see much harm in losing a single reading until the scan worker is in place, which should hopefully be ASAP.

Implementing that is rather trivial (In fact I have an implementation ready), but someone has to decide on what the interface should look like (simplest case would be to keep the current interface and make threading a pure implementation detail).

**Comment by dcyoung** [comment]
@MikeGitb 
Yes, our definition of rotation is defined as 0deg -> 360 deg, which matches the devices physical 0 degree marker. While every application could ideally parse and process the readings to handle them intelligently, we want to make it as simple as possible for users to interpret the return from `get_scan`.

I agree that the worker thread should be hidden in the implementation.

**Comment by MikeGitb** [comment]
@dcyoung: Well as I said in other threads, I generally prefer to give the User control over if they want to use threads or not (and possibly even allow them to provide the thread themselves). But if simplicity is most important to you I can probably create a PR.

**Comment by dcyoung** [comment]
I'm not against allowing the user to specify the use of threading, but we'd definitely want the base behavior (ie: the simple versions of everything) to use threading in their implementation. This is a bit off topic for this  PR though. Let's keep that discussion in #31

**Pull request merged**
