### PR TITLE
character size must be set AFTER clearing character size bits

### PR DESCRIPTION
**Pull request by vitorboschi**
Fix another issue in Linux serial port configuration, which causes the issue #72

### CODE REVIEW

**Comment by daniel-j-h** [comment]
Urgh I fail to see why it worked before then? @dcyoung any ideas here?

**Comment by dcyoung** [comment]
No clue why it worked before this. But judging by the serial guide for posix systems [here](https://www.cmrr.umn.edu/~strupp/serial.html), it looks like this PR is the correct order. If it isn't introducing any unexpected behavior on linux, then I'd advocate we merge.

**Comment by daniel-j-h** [comment]
Just tested this branch with my device on Linux - worked fine.

**Comment by daniel-j-h** [comment]
I just did a new release: https://github.com/scanse/sweep-sdk/releases

**Pull request merged**
